### ISSUE TITLE
天哥小姐姐你好，这插件做成那样子会不会更好一点

### ISSUE THREAD

**Issue by mlzzen** [csvwolf/restc-chrome-extension#4]
这个插件做成那种点一下，就打开一个页面，可以在那里调试接口，这样是不是更方便? 相当于“Restlet Client - REST API Testing”  这个插件。

**Comment by csvwolf** [comment]
你好，这个插件并不是 POSTMAN 或者是 PAW 的替代品，而是为了方便调试在原有网页中加一层 middleware，这样可以不用考虑手写 Cookie 的问题等等。
